name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # 'actions/checkout@v2' checks out your repository so the workflow can access it.

      - name: Install dependencies
        run: npm install
        # Installs dependencies listed in 'package.json'.

      - name: Build
        run: npm start build
        # Runs the build script, typically to compile or bundle code.

      - name: Run tests
        run: npm test
        # Executes your test suite to ensure code c
