name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GLOBAL_ENV_VAR: "Production"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Print environment variable
        run: echo "Env $GLOBAL_ENV_VAR"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with token
        run: echo "Deploying with token ${{ secrets.DEPLOY_TOKEN }}"
