# .github/workflows/node.js.yml
# Name of the workflow
name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x,16.x]
    # Steps will be defined next
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  # 'actions/checkout@v2' is a pre-made action that checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
  with:
          node-version: ${{ matrix.node-version }}

- name: Install dependencies
  run: npm ci
  # 'npm install' installs the dependencies defined in your project's 'package.json' file.

- name: Build (if script is present)
run: npm run build --if-present

